# fly.toml app configuration file generated for sn-bindgen-web on 2023-05-07T19:16:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sn-bindgen-web"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"

[mounts]
  source="sn_bindgen_web_data"
  destination="/var/data/bindgen-web"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "10s"
  interval = "10s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"
