#
name: Build app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    env:
      JAVA_OPTS: -Xmx6G
      UNIT_VERSION: 1.34.1
      LLVM_VERSION: 17

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - run: |
          sudo apt-get update && \
          sudo apt-get install -y curl build-essential libpcre2-dev && \
          sudo apt install -y lsb-release wget software-properties-common gnupg && \
          curl -Lo llvm.sh https://apt.llvm.org/llvm.sh && \
          chmod +x llvm.sh && \
          sudo ./llvm.sh $LLVM_VERSION && \
          sudo apt update && \
          sudo apt install -y libclang-$LLVM_VERSION-dev libz-dev libutf8proc-dev && \

          echo "LLVM_BIN=/usr/lib/llvm-$LLVM_VERSION/bin" >> $GITHUB_ENV

      - run: ./publish-forks.sh

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ matrix.OS }}-sbt-vcpkg


      - name: Build the app
        run: sbt buildApp

