#
name: Build app

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    env:
      JAVA_OPTS: -Xmx6G

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - run: brew install autoconf automake ninja libtool

      - run: ./publish-forks.sh

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ matrix.OS }}-sbt-vcpkg

      - name: Build the app
        run: sbt buildApp

