name: Build
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions/setup-earthly@v1
      with:
        version: v0.7.6
    - uses: actions/checkout@v2
    
    - name: Dockerhub login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

    - name: Run main build
      if: github.ref == 'refs/heads/main'
      run: earthly --ci --output --push +docker

    - name: Run PR build
      if: github.ref != 'refs/heads/main'
      run: earthly --ci --output +docker

    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to fly.io
      run: "flyctl deploy -a sn-bindgen-web -i bindgen-web:latest --local-only -c fly.toml"
      if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
